# Generated by Django 5.1.7 on 2025-04-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='push',
            name='user',
            field=models.IntegerField(),
        ),
    ]
