# Generated by Django 5.1.7 on 2025-04-08 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_alter_push_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='push',
            old_name='user',
            new_name='user_id',
        ),
    ]
